Introduce backend
FRIDA-api/marketplace pull request #20
Opened 2024-03-15 09:13 UTC by Laura-Schmidt-ls

# Checklist for the code review
[] The code is properly commented if needed   
[] The code has no errors   
[] The implentation is according to the requirements   
[] The code is coherent to all naming- and architecture conventions   
[] The tests were enhanced or new tests were added when needed (unit tests and e2e tests)

2024-03-25 19:27 UTC, Jonas-Knebel requested changes

2024-03-25 19:27 UTC, Jonas-Knebel commented on marketplace/angular.json
> +              "fileReplacements": [
Idk, ob wir das überhaupt mit environments lösen tbh

2024-03-25 19:27 UTC, Jonas-Knebel commented on marketplace/src/environments/environment.development.ts
> +export const environment = {
Würde ich rauslassen bis wir wissen wie wir Staging machen.

2024-03-25 19:27 UTC, Jonas-Knebel commented on marketplace/src/environments/environment.ts
> +export const environment = {
Würde ich rauslassen bis wir wissen wie wir Staging machen.

2024-03-25 19:27 UTC, Jonas-Knebel commented on marketplace/src/app/pages/api-documentation/api-documentation.component.ts
> +      default: return ""
;

2024-03-25 19:27 UTC, Jonas-Knebel commented on marketplace/src/app/pages/api-documentation/api-documentation.component.ts
> +      if (data === "") {
Nehm isEmpty() dann deckst du auch undefined und null ab.

2024-03-25 19:27 UTC, Jonas-Knebel commented on marketplace/src/app/pages/api-documentation/api-documentation.component.ts
> +    if (repository === "") {
Nehm isEmpty() dann deckst du auch undefined und null ab.

2024-03-25 19:31 UTC, Laura-Schmidt-ls commented on marketplace/angular.json
> +              "fileReplacements": [
Bin ich mir auch nicht sicher. Hatte mal gegooglet wie man sowas machen kann und fand das mit Environments ganz ansprechend. Bin da aber für jegliche Vorschläge offen. Wie würde man das mit der Backend URL machen, wenn man die Environments nicht hat?

2024-03-25 19:45 UTC, Jonas-Knebel commented on marketplace/angular.json
> +              "fileReplacements": [
Wir machen das auf Arbeit immer mit relativen URLs also ./... und dann geht der auf die gleiche domain auf der das deployt ist.

2024-03-25 20:17 UTC, Laura-Schmidt-ls commented on marketplace/angular.json
> +              "fileReplacements": [
Achso ja gut, wir wissen aber ja noch nicht auf welcher Domain das deployed sein wird. Und wie klappt das wenn du von lokal entwickelst und auf das Prod Backend zugreifen willst. Dann hast du ja auch nicht die gleiche DOmain oder?

2024-03-25 20:27 UTC, TomSchmanke commented on marketplace/angular.json
> +              "fileReplacements": [
Wir nutzen auf Arbeit auch Environments, allerdings hauptsächlich für Test Konfiguration. Die Daten kommen bei uns sonst aus GitLab oder Helm. Weil wir beides nicht haben werden finde ich Envs hier gar nicht so schlecht

2024-07-09 16:48 UTC, Laura-Schmidt-ls commented
no backend needed anymore

2024-07-09 16:48 UTC, closed without merging